Repository ublue-os/main, pull requests merged in 2024-10, with the labels that each got.

#636 feat: use negativo17 in lieu of rpmfusion
  .github/workflows/reusable-build.yml
  Containerfile
  install.sh
  packages.json
Labels: enhancement, size:M, lgtm

#645 chore: revert change of gstreamer-plugins
  packages.json
Labels: dependencies, size:XS, lgtm

#649 fix: bug in negativo prioritization command
  install.sh
Labels: bug, size:XS, lgtm

#638 feat: enable Fedora 41 builds
  .github/workflows/build-41.yml
  install.sh
  packages.json
Labels: enhancement, size:M, lgtm

#654 fix: handle new F41 selinux policies for sulogin-generator
  install.sh
  sys_files/usr/lib/systemd/system-generators/ublue-sulogin-generator
Labels: size:M, lgtm

#655 feat: add missing packages to Fedora 41 builds
  install.sh
  packages.json
Labels: enhancement, size:S, lgtm

#658 chore: ensure gnome software doesn't confuse users about dkms MOK
  install.sh
Labels: size:XS, lgtm

#657 Feat: Update tags for F41 Release
  .github/workflows/reusable-build.yml
Labels: enhancement, autorelease: pending, size:S, lgtm

#659 fix: remove redundant and less performant thumbnailer
  packages.json
Labels: size:XS, lgtm

#660 fix(kinoite): Include missing KDE image format codecs
  packages.json
Labels: size:XS, lgtm

#662 chore: consistently remove rpm-ostree backend from software stores
  packages.json
Labels: size:XS, lgtm

#663 fix: Override copr plugin config to use fedora chroot by default
  sys_files/usr/share/dnf/plugins/copr.vendor.conf
Labels: bug, size:S

#664 chore: Revert "fix: Override copr plugin config to use fedora chroot …
  sys_files/usr/share/dnf/plugins/copr.vendor.conf
Labels: size:S, lgtm
