Repository ublue-os/main, pull requests merged in 2024-09, with the labels that each got.

#637 feat: Remove lchsh
  Containerfile
Labels: enhancement, size:XS, lgtm

#639 fix: remove mate images
  .github/workflows/reusable-build.yml
  packages.json
Labels: bug, size:L, lgtm

#640 fix: Remove no longer needed rpm-ostree override
  install.sh
Labels: size:S, lgtm

#641 feat: add `wl-clipboard` to all images
  packages.json
Labels: enhancement, size:XS, lgtm

#642 style: remove trailing spaces
  packages.json
Labels: size:XS, lgtm
