Repository ublue-os/main, pull requests merged in 2024-08, with the labels that each got.

#621 feat: create emeritus.md
  emeritus.md
Labels: documentation, size:S, lgtm

#631 fix: Include fuse package for AppImage support
  packages.json
Labels: dependencies, size:XS, lgtm

#630 feat: add yubikey-manager
  packages.json
Labels: enhancement, size:XS, lgtm

#635 fix: Correct rpm-ostree issue that prevents rollbacks
  install.sh
  packages.json
Labels: bug, size:S, lgtm
