Repository ublue-os/main, pull requests merged in 2024-11, with the labels that each got.

#665 fix: Override copr plugin config to use fedora chroot by default (resubmission)
  sys_files/usr/share/dnf/plugins/copr.vendor.conf
Labels: size:S, lgtm

#671 feat: Replace gnome-software with non-dkms version on F41 and above.
  install.sh
Labels: enhancement, size:S, lgtm

#571 fix: github release install silently fails if no urls found
  github-release-install.sh
Labels: size:S, lgtm

#680 feat(ci): add registry cleanup script
  .github/workflows/clean.yml
Labels: enhancement, size:S, lgtm

#685 chore: remove kcron package
  packages.json
Labels: size:XS, lgtm
