Repository ublue-os/main, pull requests merged in 2024-07, with the labels that each got.

#601 chore: update cosign public key
  cosign.pub
Labels: size:XS, lgtm

#605 feat: use cached kernel
  .github/workflows/reusable-build.yml
  Containerfile
  install.sh
Labels: enhancement, size:M, lgtm

#603 docs: fix link to contribution guide in PR template
  .github/pull_request_template.md
Labels: documentation, size:XS, lgtm

#604 feat: Improve Containerfile / enable workflow usage of containerized buildah (tag: v1)
  .github/workflows/reusable-build.yml
  Containerfile
  github-release-install.sh
  install.sh
  packages.sh
  post-install.sh
Labels: enhancement, size:L, lgtm

#610 Revert "feat: Improve Containerfile / enable workflow usage of containerized buildah (tag: v1)"
  .github/workflows/reusable-build.yml
  Containerfile
  github-release-install.sh
  install.sh
  packages.sh
  post-install.sh
Labels: bug, size:L, lgtm

#611 chore(ci): Ensure image has signed kernels
  .github/workflows/reusable-build.yml
Labels: size:M, lgtm

#612 chore(ci): Reduce copy layers
  .github/workflows/reusable-build.yml
  Containerfile
  cleanup.sh
  initramfs.sh
  install.sh
  packages.sh
  post-install.sh
Labels: size:M, lgtm

#616 feat: add fprint and libcamera
  packages.json
Labels: enhancement, dependencies, size:XS, lgtm

#607 feat(ci): honor `IMAGE_REGISTRY` in Containerfile
  .github/workflows/reusable-build.yml
  Containerfile
Labels: enhancement, size:S, lgtm
