Repository ublue-os/main, pull requests merged in 2025-03, with the labels that each got.

#751 fix(install.sh): There is no need now to manually remove `mesa-libglapi`
  install.sh
Labels: bug, size:XS, lgtm

#757 ci: use best-practices preset for renovate config
  renovate.json
Labels: dependencies, size:S, lgtm

#722 chore: enable F42 images
  .github/workflows/build-42.yml
  .github/workflows/reusable-build.yml
  Containerfile
  build_files/github-release-install.sh
  build_files/install.sh
  build_files/packages.sh
  build_files/post-install.sh
  cleanup.sh
  initramfs.sh
  install.sh
  packages.json
  post-install.sh
Labels: size:L, lgtm

#764 Revert "chore: enable F42 images"
  .github/workflows/build-42.yml
  .github/workflows/reusable-build.yml
  Containerfile
  build_files/install.sh
  build_files/post-install.sh
  cleanup.sh
  github-release-install.sh
  initramfs.sh
  install.sh
  packages.json
  packages.sh
  post-install.sh
Labels: size:L

#766 feat: Switch to dnf5, F42
  .github/workflows/build-42.yml
  .github/workflows/reusable-build.yml
  Containerfile
  build_files/check-build.sh
  build_files/github-release-install.sh
  build_files/install.sh
  build_files/packages.sh
  build_files/post-install.sh
  cleanup.sh
  initramfs.sh
  install.sh
  packages.json
  post-install.sh
Labels: enhancement, size:XL, lgtm

#753 chore: add ublue-os/approvers as CODEOWNERS
  .github/CODEOWNERS
Labels: proposal, size:XS, lgtm

#771 fix: change just's Chinese readme file name to prevent deploy issues
  build_files/post-install.sh
Labels: bug, size:XS, lgtm

#774 fix: ensure xorg-x11-xauth package is installed
  packages.json
Labels: bug, size:XS, lgtm

#775 fix(install.sh): Intel video GPU acceleration
  build_files/install.sh
Labels: size:XS, lgtm

#776 chore: add intel hw-accel to f42
  build_files/install.sh
Labels: size:XS, lgtm

#777 chore: add uncrippled mesa to F42
  build_files/install.sh
Labels: size:S, lgtm
