Repository ublue-os/main, pull requests merged in 2025-04, with the labels that each got.

#767 chore: cleanup packages.sh
  build_files/packages.sh
  packages.json
Labels: size:L, lgtm

#784 chore: Fix missing xhost on some images.
  packages.json
Labels: size:XS, lgtm

#785 feat: bump latest to F42, bump GTS to F41
  .github/workflows/reusable-build.yml
Labels: enhancement, size:S, lgtm

#788 feat: add cosmic build
  .github/workflows/build-42.yml
Labels: enhancement, size:XS, lgtm

#755 chore(packages): Remove `gnome-epub-thumbnailer`
  packages.json
Labels: size:XS, lgtm

#790 chore: remove images no longer published by upstream
  .github/workflows/build-40.yml
Labels: size:XS, lgtm

#794 fix(repo): correct automerge casing
  .github/renovate.json5
Labels: size:XS

#782 fix(packages): remove gnome-tweaks
  packages.json
Labels: size:XS, lgtm

#798 fix(ci): group and automerge akmods updates
  .github/renovate.json5
Labels: size:S

#786 chore: deprecate Fedora 40
  .github/workflows/build-40.yml
  .github/workflows/reusable-build.yml
  Justfile
  README.md
  build_files/install.sh
  build_files/post-install.sh
  image-versions.yaml
  packages.json
Labels: documentation, size:L, lgtm

#815 chore: remove image-versions from codeowners
  .github/CODEOWNERS
Labels: size:XS, lgtm

#814 fix: use digest when extracting kernel versions
  .github/renovate.json5
  .github/workflows/reusable-build.yml
Labels: size:S, lgtm

#813 chore(nvidia): moving nvidia builds from hwe to main
  .github/renovate.json5
  .github/workflows/build-41.yml
  .github/workflows/build-42.yml
  .github/workflows/reusable-build.yml
  Containerfile
  build_files/nvidia-install.sh
  image-versions.yaml
Labels: enhancement, size:L, lgtm

#820 chore(ci): bundle nvidia-akmods updates into images group
  .github/renovate.json5
Labels: dependencies, size:XS, lgtm

#825 fix: sway-atomic not getting proper env file on nvidia
  build_files/nvidia-install.sh
Labels: bug, size:XS, lgtm

#828 change: add noelmiller to emeritus
  emeritus.md
Labels: documentation, size:XS, lgtm

#832 fix: ensure initramfs is generated after nvidia driver install
  Containerfile
  build_files/initramfs.sh
  build_files/install.sh
Labels: size:S, lgtm

#823 chore(ci): remove scheduled cronjobs
  .github/workflows/build-41.yml
  .github/workflows/build-42.yml
Labels: size:XS, lgtm
