Repository ublue-os/main, pull requests merged in 2025-05, with the labels that each got.

#770 feat: cleanup justfile and use just to build
  .devcontainer/Containerfile
  .devcontainer/devcontainer.json
  .devcontainer/local-features/podman/devcontainer-feature.json
  .devcontainer/local-features/podman/install.sh
  .devcontainer/local-features/tools/devcontainer-feature.json
  .devcontainer/local-features/tools/install.sh
  .github/workflows/build-beta.yml
  .github/workflows/build-gts.yml
  .github/workflows/build-latest.yml
  .github/workflows/reusable-build.yml
  .vscode/tasks.json
  Containerfile
  Justfile
  boot_menu.yml
  just_scripts/build-image.sh
  just_scripts/build-iso-installer-main.sh
  just_scripts/build-iso-makefile-patch
  just_scripts/build-iso.sh
  just_scripts/cleanup-dir.sh
  just_scripts/cleanup-images.sh
  just_scripts/container_mgr.sh
  just_scripts/get-defaults.sh
  just_scripts/list-images.sh
  just_scripts/run-image.sh
  just_scripts/run-iso.sh
  just_scripts/sudoif.sh
Labels: enhancement, size:XXL, lgtm

#856 fix(ci): Get Digest from the remote for signing
  Justfile
Labels: size:XS, lgtm

#860 fix: IMAGE_NAME Build arg should not have -main or -nvidia
  Justfile
Labels: size:XS, lgtm

#863 chore(ci): retry podman push
  Justfile
Labels: enhancement, size:XS, lgtm

#887 fix: stop renovate from updating dev container
  .devcontainer/Containerfile
  .github/renovate.json5
Labels: dependencies, size:XS, lgtm

#891 fix: ensure kmod-nvidia version matches nvidia-driver
  build_files/nvidia-install.sh
Labels: bug, size:XS, lgtm
