Repository ublue-os/main, pull requests merged in 2025-06, with the labels that each got.

#929 chore: deprecate images not used by final images
  .github/workflows/build-beta.yml
  .github/workflows/build-gts.yml
  .github/workflows/build-latest.yml
  Justfile
  README.md
Labels: documentation, size:S, lgtm

#914 feat: update emeritus.md
  emeritus.md
Labels: documentation, size:XS, lgtm

#913 feat: add fcitx5 packages
  packages.json
Labels: enhancement, size:S, lgtm

#943 fix: Revert "feat: add fcitx5 packages (#913)"
  packages.json
Labels: bug, size:S, lgtm

#949 fix: versionlock QT6 and add fcitx packages back
  build_files/install.sh
  packages.json
Labels: bug, size:S, lgtm

#1001 fix: remove kernel-uki-virt
  build_files/install.sh
Labels: bug, size:XS, lgtm
