Repository ublue-os/main, pull requests merged in 2025-02, with the labels that each got.

#713 chore(ci): delete .github/dependabot.yml
  .github/dependabot.yml
Labels: dependencies, size:S, lgtm

#719 fix: remove dependency on kernel images
  .github/workflows/reusable-build.yml
  Containerfile
Labels: dependencies, size:S, lgtm

#718 chore: remove F39 workflow and refactor matrixes
  .github/workflows/build-39.yml
  .github/workflows/build-40.yml
  .github/workflows/build-41.yml
  .github/workflows/reusable-build.yml
Labels: size:L, lgtm

#679 chore: remove cliwrap and call dracut directly
  initramfs.sh
  install.sh
Labels: size:XS, lgtm

#721 chore: remove alternatives workaround
  Containerfile
Labels: size:XS, lgtm

#723 chore: remove mesa-libglapi unused dep
  install.sh
Labels: dependencies, size:M, lgtm

#724 refactor: use ublue-os/packages COPR rather than config image
  Containerfile
  install.sh
Labels: size:XS, lgtm

#746 chore: rm packages copr /cp containers/policy.json
  install.sh
  post-install.sh
Labels: size:XS, lgtm
